# Generated by Django 5.2.11 on 2026-08-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobber_app", "0006_ghl_contact_jobber_client_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobberTaskIdempotency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("jobber_task_id", models.CharField(db_index=True, max_length=255)),
                (
                    "jobber_web_uri",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "jobber_task_idempotency",
                "ordering": ["-created_at"],
            },
        ),
    ]
