# Generated by Django 4.2.7 on 2025-07-31 14:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionpricing',
            name='pricing_type',
            field=models.CharField(choices=[('upcharge_percent', 'Fixed Upcharge Amount'), ('discount_percent', 'Fixed Discount Amount'), ('fixed_price', 'Fixed Price'), ('ignore', 'Ignore')], default='ignore', max_length=20),
        ),
        migrations.AlterField(
            model_name='optionpricing',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed amount to add/subtract (e.g., 12.00 for $12)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='questionpricing',
            name='yes_pricing_type',
            field=models.CharField(choices=[('upcharge_percent', 'Fixed Upcharge Amount'), ('discount_percent', 'Fixed Discount Amount'), ('fixed_price', 'Fixed Price'), ('ignore', 'Ignore')], default='ignore', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionpricing',
            name='yes_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed amount to add/subtract (e.g., 12.00 for $12)', max_digits=10),
        ),
    ]
