# Generated by Django 4.2.7 on 2025-08-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_disclaimer', models.TextField(blank=True, null=True)),
                ('bid_in_person_disclaimer', models.TextField(blank=True, null=True)),
                ('apply_area_minimum', models.BooleanField(default=False)),
                ('apply_house_size_minimum', models.BooleanField(default=False)),
                ('apply_trip_charge_to_bid', models.BooleanField(default=False)),
                ('enable_dollar_minimum', models.BooleanField(default=False)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='service_app.service')),
            ],
        ),
    ]
