# Generated by Django 4.2.7 on 2025-08-04 17:30

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_servicesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('yes_no_answer', models.BooleanField(blank=True, null=True)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_responses',
            },
        ),
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_question_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sub_questions',
                'ordering': ['order', 'sub_question_text'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='condition_answer',
            field=models.CharField(blank=True, help_text="Answer value that triggers this conditional question (e.g., 'yes', 'no', or option ID)", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='condition_option',
            field=models.ForeignKey(blank=True, help_text='Option that triggers this conditional question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditional_questions', to='service_app.questionoption'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_questions', to='service_app.question'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='allow_quantity',
            field=models.BooleanField(default=False, help_text='Allow quantity input for this option'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='max_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum allowed quantity'),
        ),
        migrations.AlterField(
            model_name='optionpricing',
            name='pricing_type',
            field=models.CharField(choices=[('upcharge_percent', 'Fixed Upcharge Amount'), ('discount_percent', 'Fixed Discount Amount'), ('fixed_price', 'Fixed Price'), ('per_quantity', 'Price Per Quantity'), ('ignore', 'Ignore')], default='ignore', max_length=20),
        ),
        migrations.AlterField(
            model_name='optionpricing',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed amount to add/subtract (e.g., 12.00 for $12) or price per quantity', max_digits=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes/No'), ('describe', 'Describe (Multiple Options)'), ('multiple_yes_no', 'Multiple Yes/No Sub-Questions'), ('conditional', 'Conditional Questions'), ('quantity', 'How Many (Quantity Selection)')], max_length=20),
        ),
        migrations.CreateModel(
            name='SubQuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_question_responses', to='service_app.questionresponse')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.subquestion')),
            ],
            options={
                'db_table': 'sub_question_responses',
            },
        ),
        migrations.AddField(
            model_name='subquestion',
            name='parent_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='service_app.question'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.question'),
        ),
        migrations.CreateModel(
            name='OptionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.questionoption')),
                ('question_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_responses', to='service_app.questionresponse')),
            ],
            options={
                'db_table': 'option_responses',
            },
        ),
        migrations.CreateModel(
            name='SubQuestionPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('yes_pricing_type', models.CharField(choices=[('upcharge_percent', 'Fixed Upcharge Amount'), ('discount_percent', 'Fixed Discount Amount'), ('fixed_price', 'Fixed Price'), ('ignore', 'Ignore')], default='ignore', max_length=20)),
                ('yes_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Fixed amount to add/subtract for 'Yes' answer", max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_question_pricing', to='service_app.package')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='service_app.subquestion')),
            ],
            options={
                'db_table': 'sub_question_pricing',
                'unique_together': {('sub_question', 'package')},
            },
        ),
    ]
