# Generated by Django 4.2.7 on 2025-08-05 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_questionresponse_subquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSizePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_sqft', models.PositiveIntegerField()),
                ('max_sqft', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'min_sqft'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackageSizeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('global_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.globalsizepackage')),
                ('service_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_pricings', to='service_app.package')),
            ],
            options={
                'ordering': ['global_size__order'],
                'unique_together': {('service_package', 'global_size')},
            },
        ),
        migrations.CreateModel(
            name='GlobalPackageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('global_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_prices', to='service_app.globalsizepackage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('global_size', 'label')},
            },
        ),
    ]
