# Generated by Django 4.2.7 on 2025-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_globalsizepackage_servicepackagesizemapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsizepackage',
            name='max_sqft',
            field=models.PositiveIntegerField(blank=True, default=100000000, null=True),
        ),
    ]
