# Generated by Django 4.2.7 on 2025-08-25 15:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_alter_globalsizepackage_max_sqft'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'property_types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='globalsizepackage',
            options={'ordering': ['property_type__order', 'order', 'min_sqft']},
        ),
        migrations.AlterModelOptions(
            name='servicepackagesizemapping',
            options={'ordering': ['global_size__property_type__order', 'global_size__order']},
        ),
        migrations.AddField(
            model_name='globalpackagetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsizepackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepackagesizemapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name='globalpackagetemplate',
            table='global_package_templates',
        ),
        migrations.AlterModelTable(
            name='globalsizepackage',
            table='global_size_packages',
        ),
        migrations.AlterModelTable(
            name='servicepackagesizemapping',
            table='service_package_size_mappings',
        ),
        migrations.AddField(
            model_name='globalsizepackage',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_packages', to='service_app.propertytype'),
        ),
        migrations.AlterUniqueTogether(
            name='globalsizepackage',
            unique_together={('property_type', 'min_sqft', 'max_sqft')},
        ),
    ]
