# Generated by Django 4.2.7 on 2025-08-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0009_addonservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionpricing',
            name='value_type',
            field=models.CharField(choices=[('amount', 'Amount'), ('percent', 'Percentage')], default='amount', max_length=20),
        ),
        migrations.AddField(
            model_name='questionpricing',
            name='value_type',
            field=models.CharField(choices=[('amount', 'Amount'), ('percent', 'Percentage')], default='amount', max_length=20),
        ),
        migrations.AddField(
            model_name='subquestionpricing',
            name='value_type',
            field=models.CharField(choices=[('amount', 'Amount'), ('percent', 'Percentage')], default='amount', max_length=20),
        ),
    ]
