# Generated by Django 4.2.7 on 2025-08-26 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0010_optionpricing_value_type_questionpricing_value_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('amount', 'Fixed Amount')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=10)),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity in total required for this discount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_discounts', to='service_app.question')),
            ],
            options={
                'db_table': 'quantity_discounts',
                'ordering': ['min_quantity'],
            },
        ),
    ]
