# Generated by Django 4.2.7 on 2025-08-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0011_quantitydiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitydiscount',
            name='option',
            field=models.ForeignKey(blank=True, help_text='Leave empty if discount is for entire question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantity_discounts', to='service_app.questionoption'),
        ),
        migrations.AddField(
            model_name='quantitydiscount',
            name='scope',
            field=models.CharField(choices=[('question', 'Apply to whole question'), ('option', 'Apply only to specific option')], default='question', max_length=20),
        ),
        migrations.AlterField(
            model_name='quantitydiscount',
            name='min_quantity',
            field=models.PositiveIntegerField(help_text='Minimum quantity required for this discount'),
        ),
    ]
