# Generated by Django 4.2.7 on 2025-08-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0012_quantitydiscount_option_quantitydiscount_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
