# Generated by Django 4.2.7 on 2025-09-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0013_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackagesizemapping',
            name='pricing_type',
            field=models.CharField(choices=[('upcharge', 'Fixed Upcharge Amount'), ('bid_in_person', 'Bid In Person')], default='upcharge', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicepackagesizemapping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
