# Generated by Django 4.2.7 on 2025-09-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0014_servicepackagesizemapping_pricing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
