# Generated by Django 4.2.7 on 2025-09-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0015_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_commercial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_residential',
            field=models.BooleanField(default=True),
        ),
    ]
