# Generated by Django 4.2.7 on 2025-09-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0016_service_is_commercial_service_is_residential'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_enable_dollar_minimum',
            field=models.BooleanField(default=False),
        ),
    ]
