# Generated by Django 4.2.7 on 2025-09-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0017_service_is_enable_dollar_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_option/'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subquestion/'),
        ),
    ]
