# Generated by Django 4.2.7 on 2025-10-06 14:24

from django.db import migrations, models
import service_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0019_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='questions/', validators=[service_app.models.validate_image_or_svg]),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='question_option/', validators=[service_app.models.validate_image_or_svg]),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='subquestion/', validators=[service_app.models.validate_image_or_svg]),
        ),
    ]
