# Generated by Django 4.2.7 on 2025-10-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0020_alter_question_image_alter_questionoption_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_value',
        ),
        migrations.AddField(
            model_name='coupon',
            name='fixed_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount discount.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='percentage_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (0-100).', max_digits=5, null=True),
        ),
    ]
