# Generated by Django 4.2.7 on 2025-11-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0021_remove_coupon_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_global',
            field=models.BooleanField(default=False, help_text='If True, this coupon can be used by all users.'),
        ),
    ]
