# Generated by Django 4.2.7 on 2025-12-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0024_user_created_by_user_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_addon_service',
            field=models.BooleanField(default=False, help_text='Access to add-on service management section'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_coupon',
            field=models.BooleanField(default=False, help_text='Access to coupon section'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_dashboard',
            field=models.BooleanField(default=True, help_text='Access to dashboard section'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_house_size_management',
            field=models.BooleanField(default=False, help_text='Access to house size management section'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_location',
            field=models.BooleanField(default=False, help_text='Access to location management section'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_on_the_go_calculator',
            field=models.BooleanField(default=False, help_text='Access to on-the-go calculator section'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_reports',
            field=models.BooleanField(default=False, help_text='Access to reports section'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_service_management',
            field=models.BooleanField(default=False, help_text='Access to service management section'),
        ),
    ]
