# Generated by Django 4.2.7 on 2025-08-05 20:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_app', '0006_globalsizepackage_servicepackagesizemapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('yes_no_answer', models.BooleanField(blank=True, null=True)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.question')),
            ],
            options={
                'db_table': 'customer_question_responses',
            },
        ),
        migrations.CreateModel(
            name='CustomerServiceSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('surcharge_applicable', models.BooleanField(default=False)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_sqft_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_app.package')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.service')),
            ],
            options={
                'db_table': 'customer_service_selections',
            },
        ),
        migrations.CreateModel(
            name='CustomerSubQuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.BooleanField()),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_question_responses', to='quote_app.customerquestionresponse')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.subquestion')),
            ],
            options={
                'db_table': 'customer_sub_question_responses',
            },
        ),
        migrations.CreateModel(
            name='CustomerSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField()),
                ('house_sqft', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('responses_completed', 'Responses Completed'), ('packages_selected', 'Packages Selected'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('total_base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_surcharges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_app.location')),
                ('selected_services', models.ManyToManyField(through='quote_app.CustomerServiceSelection', to='service_app.service')),
            ],
            options={
                'db_table': 'customer_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customerserviceselection',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote_app.customersubmission'),
        ),
        migrations.AddField(
            model_name='customerquestionresponse',
            name='service_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='quote_app.customerserviceselection'),
        ),
        migrations.CreateModel(
            name='CustomerOptionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.questionoption')),
                ('question_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_responses', to='quote_app.customerquestionresponse')),
            ],
            options={
                'db_table': 'customer_option_responses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='customerserviceselection',
            unique_together={('submission', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='customerquestionresponse',
            unique_together={('service_selection', 'question')},
        ),
        migrations.CreateModel(
            name='CustomerPackageQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sqft_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('question_adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('included_features', models.JSONField(default=list)),
                ('excluded_features', models.JSONField(default=list)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.package')),
                ('service_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_quotes', to='quote_app.customerserviceselection')),
            ],
            options={
                'db_table': 'customer_package_quotes',
                'unique_together': {('service_selection', 'package')},
            },
        ),
    ]
