# Generated by Django 4.2.7 on 2025-08-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='ghl_contact_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
