# Generated by Django 4.2.7 on 2025-08-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0002_customersubmission_ghl_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='surcharge_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
