# Generated by Django 4.2.7 on 2025-08-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0003_customersubmission_surcharge_applicable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersubmission',
            old_name='surcharge_applicable',
            new_name='quote_surcharge_applicable',
        ),
    ]
