# Generated by Django 4.2.7 on 2025-08-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0004_rename_surcharge_applicable_customersubmission_quote_surcharge_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
