# Generated by Django 4.2.7 on 2025-08-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0012_quantitydiscount_option_quantitydiscount_scope_and_more'),
        ('quote_app', '0005_customersubmission_additional_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersubmission',
            old_name='ghl_contact_id',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='house_sqft',
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='actual_sqft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='allow_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='allow_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='heard_about_us',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='is_previous_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='num_floors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='property_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='property_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='size_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_app.globalsizepackage'),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
