# Generated by Django 4.2.7 on 2025-08-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0012_quantitydiscount_option_quantitydiscount_scope_and_more'),
        ('quote_app', '0006_rename_ghl_contact_id_customersubmission_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='service_app.addonservice'),
        ),
    ]
