# Generated by Django 4.2.7 on 2025-08-27 16:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0007_customersubmission_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='total_addons_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
