# Generated by Django 4.2.7 on 2025-08-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0008_customersubmission_total_addons_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='ghl_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
