# Generated by Django 4.2.7 on 2025-09-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0009_customersubmission_ghl_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customersubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('responses_completed', 'Responses Completed'), ('packages_selected', 'Packages Selected'), ('submitted', 'Submitted'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
    ]
