# Generated by Django 4.2.7 on 2025-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0010_customersubmission_declined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='is_bid_in_person',
            field=models.BooleanField(default=False),
        ),
    ]
