# Generated by Django 4.2.7 on 2025-10-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0019_coupon'),
        ('quote_app', '0011_customersubmission_is_bid_in_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='service_app.coupon'),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='is_coupon_applied',
            field=models.BooleanField(default=False),
        ),
    ]
