# Generated by Django 4.2.7 on 2025-10-03 19:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0012_customersubmission_applied_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='discounted_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
