# Generated by Django 4.2.7 on 2025-10-14 14:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0020_alter_question_image_alter_questionoption_image_and_more'),
        ('quote_app', '0013_customersubmission_discounted_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubmission',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='applied_coupon',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='discounted_amount',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='is_coupon_applied',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='total_addons_price',
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='old_addons',
            field=models.ManyToManyField(blank=True, related_name='old_submissions', to='service_app.addonservice'),
        ),
        migrations.CreateModel(
            name='SubmissionAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_submissions', to='service_app.addonservice')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_addons', to='quote_app.customersubmission')),
            ],
            options={
                'unique_together': {('submission', 'addon')},
            },
        ),
    ]
