# Generated by Django 4.2.7 on 2025-10-14 14:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0020_alter_question_image_alter_questionoption_image_and_more'),
        ('quote_app', '0014_remove_customersubmission_addons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='submissions', through='quote_app.SubmissionAddOn', to='service_app.addonservice'),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='total_addons_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
