# Generated by Django 4.2.7 on 2025-10-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0015_customersubmission_addons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubmission',
            name='old_addons',
        ),
    ]
