# Generated by Django 4.2.7 on 2025-10-14 15:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0020_alter_question_image_alter_questionoption_image_and_more'),
        ('quote_app', '0016_remove_customersubmission_old_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='service_app.coupon'),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='discounted_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='is_coupon_applied',
            field=models.BooleanField(default=False),
        ),
    ]
