# Generated by Django 4.2.7 on 2025-10-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0017_customersubmission_applied_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='is_on_the_go',
            field=models.BooleanField(default=False),
        ),
    ]
