# Generated by Django 4.2.7 on 2025-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0018_customersubmission_is_on_the_go'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubmission',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customersubmission',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
