# Generated by Django 4.2.7 on 2025-10-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0019_alter_customersubmission_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubmission',
            name='allow_email',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='customersubmission',
            name='allow_sms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customersubmission',
            name='is_previous_customer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
