# Generated by Django 4.2.7 on 2025-10-29 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0020_alter_customersubmission_allow_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='quote_app.customersubmission')),
            ],
            options={
                'db_table': 'customer_availabilities',
                'ordering': ['date'],
                'unique_together': {('submission', 'date', 'time')},
            },
        ),
    ]
