# Generated by Django 4.2.7 on 2025-10-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0021_customeravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='edit_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='edited_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='original_final_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
