# Generated by Django 4.2.7 on 2025-10-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0022_customersubmission_edit_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='quote_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
