# Generated by Django 4.2.7 on 2025-12-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0025_customermeasurementresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('packages_selected', 'Packages Selected'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
    ]
