# Generated by Django 4.2.7 on 2025-12-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0026_alter_customersubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='bid_notes_private',
            field=models.TextField(blank=True, help_text='Private notes visible only to admins', null=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='bid_notes_public',
            field=models.TextField(blank=True, help_text='Public notes visible to customers', null=True),
        ),
    ]
