# Generated by Django 4.2.7 on 2025-12-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0028_customerpackagequote_measurement_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpackagequote',
            name='admin_override_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin override price for this specific package. If set, this will be used instead of calculated total_price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customerpackagequote',
            name='admin_override_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpackagequote',
            name='admin_override_set_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
